# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - jessfraz
      - franknoirot
      - jgomez720
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - jessfraz
      - franknoirot
      - jgomez720
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - jessfraz
      - franknoirot
      - jgomez720
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - jessfraz
      - franknoirot
      - jgomez720
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/tutorials/websocket_tutorial/draw_cube_rust/" # Location of package manifests
    schedule:
      interval: "daily"
    reviewers:
      - adamchalmers
      - jessfraz
      - franknoirot
      - jgomez720
