name: mypy
on:
  push:
    branches: main
    paths:
      - '**.py'
      - .github/workflows/mypy.yml
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    paths:
      - '**.py'
      - .github/workflows/mypy.yml
      - 'pyproject.toml'
      - 'uv.lock'
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
      - name: Install deps
        run: |
            uv venv .venv
            echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
            echo "$PWD/.venv/bin" >> $GITHUB_PATH
            uv sync

      - name: Run mypy
        shell: bash
        run: |
          mypy */*/*.py
