# adapted from:
#
# * base code: https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/
# * fix push auth: https://github.com/ad-m/github-push-action
# * checkout PR head commit https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
name: auto-format
permissions:
  packages: read
  contents: write
on:
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:
jobs:
  format:
    # Check if the PR is not from a fork
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Install deps
        run: |
          uv sync
          uv run ruff format
          uv run ruff check --fix . */*/*.py
      - name: Commit generated files
        uses: KittyCAD/gha-actions-public/pr-commit@main
        with:
          app-id: ${{ secrets.GH_ORG_APP_ID }}
          private-key: ${{ secrets.GH_ORG_APP_PRIVATE_KEY }}
          commit-message: "LOOK ON MY REFORMAT, YE MIGHTY, AND DESPAIR!"
